# Generated by Django 4.1.2 on 2022-11-21 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
