# Generated by Django 4.1.2 on 2023-07-01 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0005_remove_vendor_profile_vendor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
