# Generated by Django 4.1.2 on 2023-08-25 08:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('storeapp', '0009_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='reviewlikes', to=settings.AUTH_USER_MODEL),
        ),
    ]
