# Generated by Django 4.1.2 on 2022-12-09 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0010_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
