# Generated by Django 4.1.2 on 2022-12-09 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0011_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-price']},
        ),
    ]
